linters:
  enabled:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - bodyclose
    - dupl
    - gosec
    - varcheck
    - godox
  disable:
    - ineffassign

run:
  skip-dirs:
    - sdk/
