includes:
  - from_url:
      url: https://raw.githubusercontent.com/ory/xgoreleaser/master/build.tmpl.yml

variables:
  brew_name: kratos

  brew_description: "The Ory Kratos Identity Platform"

  buildinfo_hash: "github.com/ory/kratos/driver/config.Commit"
  buildinfo_tag: "github.com/ory/kratos/driver/config.Version"
  buildinfo_date: "github.com/ory/kratos/driver/config.Date"

project_name: kratos
