steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build and Push'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        export DOCKER_BUILDKIT=1 && \
        docker build -f Dockerfile --build-arg BUILDKIT_INLINE_CACHE=1 .
images:
  - 'gcr.io/$PROJECT_ID/kratos-fork:latest'
options:
  logging: CLOUD_LOGGING_ONLY
timeout: 3600s
