version: '3.7'

services:
  kratos-migrate:
    image: oryd/kratos:v0.8.2-alpha.1
    environment:
      - DSN=cockroach://root@cockroachd:26257/defaultdb?sslmode=disable&max_conns=20&max_idle_conns=4

  kratos:
    image: oryd/kratos:v0.8.2-alpha.1
    environment:
      - DSN=cockroach://root@cockroachd:26257/defaultdb?sslmode=disable&max_conns=20&max_idle_conns=4

  cockroachd:
    image: cockroachdb/cockroach:v21.2.4
    ports:
      - "26257:26257"
    command: start-single-node --insecure
    networks:
      - intranet
