- op: replace
  path: /components/securitySchemes/oryToken
  value:
    type: http
    scheme: bearer

- op: replace
  path: /components/securitySchemes/sessionToken
  value:
    type: http
    scheme: bearer
