# serve controls the configuration for the http(s) daemon
serve:
  admin:
    port: 1234
    host: admin.kratos.ory.sh
  public:
    port: 1235
    host: public.kratos.ory.sh

dsn: sqlite://foo.db?mode=memory&_fk=true

log:
  level: debug

courier:
  smtp:
    connection_uri: smtp://foo:bar@baz/

urls:
  default_return_to: http://return-to-3-test.ory.sh/
  mfa_ui: http://test.kratos.ory.sh/mfa
  login_ui: http://test.kratos.ory.sh/login
  settings_ui: http://test.kratos.ory.sh/settings
  verify_ui: http://test.kratos.ory.sh/verify
  registration_ui: http://test.kratos.ory.sh/register
  self:
    public: http://public.kratos.ory.sh
    admin: http://admin.kratos.ory.sh
  error_ui: http://test.kratos.ory.sh/error
  whitelisted_return_to_urls:
    - http://return-to-1-test.ory.sh/
    - http://return-to-2-test.ory.sh/

identity:
  traits:
    default_schema_url: http://test.kratos.ory.sh/default-identity.schema.json
    schemas:
      - id: other
        url: http://test.kratos.ory.sh/other-identity.schema.json

hashers:
  argon2:
    memory: 1048576
    iterations: 2
    parallelism: 4
    salt_length: 16
    key_length: 32

secrets:
  session:
    - session-key-7f8a9b77-1
    - session-key-7f8a9b77-2

selfservice:
  strategies:
    password:
      enabled: true
    oidc:
      enabled: true
      config:
        providers:
          - id: github
            provider: github
            client_id: a
            client_secret: b
            mapper_url: http://test.kratos.ory.sh/default-identity.schema.json
  logout:
    redirect_to: http://test.kratos.ory.sh:4000/

  settings:
    request_lifespan: 99m
    privileged_session_max_age: 5m
    after:
      default_return_to: https://self-service/settings/return_to
      password:
        default_return_to: https://self-service/settings/password/return_to
      profile:
        hooks:
          -
            hook: verify
  login:
    request_lifespan: 99m
    before:
      hooks:
        - hook: redirect
          config:
            default_redirect_url: http://test.kratos.ory.sh:4000/
            allow_user_defined_redirect: false
    after:
      default_return_to: https://self-service/login/return_to
      password:
        default_return_to: https://self-service/login/password/return_to
        hooks:
          -
            hook: revoke_active_sessions
      oidc:
        hooks:
          -
            hook: revoke_active_sessions
  registration:
    request_lifespan: 98m
    before:
      hooks:
        - hook: redirect
          config:
            default_redirect_url: http://test.kratos.ory.sh:4000/
            allow_user_defined_redirect: false
    after:
      default_return_to: https://self-service/registration/return_to
      password:
        hooks:
          -
            hook: session
          -
            hook: verify
          - hook: redirect
            config:
              default_redirect_url: http://test.kratos.ory.sh:4000/
              allow_user_defined_redirect: false
      oidc:
        default_return_to: https://self-service/registration/oidc/return_to
        hooks:
          -
            hook: verify
          -
            hook: session
          - hook: redirect
            config:
              default_redirect_url: http://test.kratos.ory.sh:4000/
              allow_user_defined_redirect: false

#      - job: account_activation
#        config:
#          redirect:
#            pending:
#            success:
#            invalidate_after: 10h
