# serve controls the configuration for the http(s) daemon
serve:
  admin:
    port: 1234
    host: admin.kratos.ory.sh
  public:
    port: 1235
    host: public.kratos.ory.sh

dsn: sqlite://foo.db?mode=memory&_fk=true

log:
  level: debug

courier:
  smtp:
    connection_uri: smtp://foo:bar@baz/

urls:
  default_return_to: http://return-to-3-test.ory.sh/
  mfa_ui: http://test.kratos.ory.sh/mfa
  login_ui: http://test.kratos.ory.sh/login
  profile_ui: http://test.kratos.ory.sh/profile
  verify_ui: http://test.kratos.ory.sh/verify
  registration_ui: http://test.kratos.ory.sh/register
  self:
    public: http://public.kratos.ory.sh
    admin: http://admin.kratos.ory.sh
  error_ui: http://test.kratos.ory.sh/error
  whitelisted_return_to_domains:
    - http://return-to-1-test.ory.sh/
    - http://return-to-2-test.ory.sh/

identity:
  traits:
    default_schema_url: http://test.kratos.ory.sh/default-identity.schema.json
    schemas:
      - id: other
        url: http://test.kratos.ory.sh/other-identity.schema.json

hashers:
  argon2:
    memory: 1048576
    iterations: 2
    parallelism: 4
    salt_length: 16
    key_length: 32

secrets:
  session:
    - session-key-7f8a9b77-1
    - session-key-7f8a9b77-2

selfservice:
  strategies:
    password:
      enabled: true
    oidc:
      enabled: true
      config:
        providers:
          - id: github
            provider: github
            client_id: a
            client_secret: b
            schema_url: http://test.kratos.ory.sh/default-identity.schema.json
  logout:
    redirect_to: http://test.kratos.ory.sh:4000/
  login:
    request_lifespan: 99m
    before:
      - job: redirect
        config:
          default_redirect_url: http://test.kratos.ory.sh:4000/
          allow_user_defined_redirect: false
    after:
      password:
        -
          job: revoke_active_sessions
        - job: session
        - job: redirect
          config:
            default_redirect_url: http://test.kratos.ory.sh:4000/
            allow_user_defined_redirect: true
      oidc:
        -
          job: revoke_active_sessions
        - job: session
        - job: redirect
          config:
            default_redirect_url: http://test.kratos.ory.sh:4000/
            allow_user_defined_redirect: true
  registration:
    request_lifespan: 98m
    before:
      - job: redirect
        config:
          default_redirect_url: http://test.kratos.ory.sh:4000/
          allow_user_defined_redirect: false
    after:
      password:
        -
          job: session
        -
          job: redirect
          config:
            default_redirect_url: http://test.kratos.ory.sh:4000/
            allow_user_defined_redirect: true
      oidc:
        -
          job: session
        -
          job: redirect
          config:
            default_redirect_url: http://test.kratos.ory.sh:4000/
            allow_user_defined_redirect: true

#      - job: account_activation
#        config:
#          redirect:
#            pending:
#            success:
#            invalidate_after: 10h