on:
  schedule:
    - cron: '0 7 * * *'

jobs:
  find_closed_references:
    runs-on: ubuntu-latest
    name: Find closed references
    steps:
      - uses: actions/checkout@v2
      - uses: ory/closed-reference-notifier@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore: .git,**/node_modules,docs,CHANGELOG.md,.bin
          issueLabels: upstream
          issueLimit: 5
